[package]
name = "gherrit"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
gix = "0.75.0"
rayon = "1.11.0"
regex = "1.12.2"
serde = { version = "1.0.228", features = ["serde_derive"] }
serde_json = "1.0.145"
log = "0.4"
env_logger = "0.11"
